[build]
  publish = "public"
  command = "hugo"

[[headers]]
  for = "/files/*"
  [headers.values]
  Content-Type = "application/octet-stream"
  Content-Disposition = "attachment"
  Cache-Control = "public, max-age=31536000"