backend:
    name: git-gateway
    branch: main

media_folder: static/uploads
public_folder: /uploads

collections:
    - name: 'notice'
      label: '공지사항'
      folder: 'content/notice'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      fields:
          - { label: '제목', name: 'title', widget: 'string' }
          - { label: '본문', name: 'body', widget: 'markdown' }
